pipeline {
    agent any

    tools {
        gradle "grdl7.4.1"
    }

    stages {
        stage('Build') {
            steps {
                sh "gradle :service:clean :service:build"
            }
        }
        stage('Test') {
            steps {
                sh "gradle :service:test"
            }
        }
        stage('Deploy') {
            steps {
                sh "gradle :service:deployHeroku"
            }
        }
    }
}
