pipeline {
    agent any

    tools {
        gradle "grdl7.4.1"
    }

    stages {
        stage('Build') {
            steps {
                dir('back') {
                  sh "gradle :service:clean :service:build"
                }
            }
        }
        stage('Test') {
            steps {
                dir('back') {
                    sh "gradle :service:test"
                }
            }
        }
      stage('SonarQube') {
        withSonarQubeEnv() {
          sh './gradlew sonarqube'
        }
      }
    }
}
