server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Cinema
    username: postgres
    password: bartiq132
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher