pipeline {
  agent {
    docker {
      image 'node:latest'
    }
  }

  stages {
    stage('install') {
      steps {
        dir('front') {
          sh 'npm install'
        }
      }
    }

    stage('build') {
      steps {
        dir('front') {
          sh 'npm run-script build'
        }
      }
    }

    stage('test') {
      steps {
        dir('front') {
          sh 'npm run-script test'
        }
      }
    }
  }
}
