pipeline {
  agent any

  stages {
    stage('install') {
      steps {
        dir('front') {
          nodejs(nodeJSInstallationName: 'nodejs') {
              sh 'npm install'
          }
        }
      }
    }

    stage('build') {
      steps {
        dir('front') {
          nodejs(nodeJSInstallationName: 'nodejs') {
              sh 'npm run-script build'
          }
        }
      }
    }

    stage('test') {
      steps {
        dir('front') {
          nodejs(nodeJSInstallationName: 'nodejs') {
              sh 'npm run-script test'
          }
        }
      }
    }

  }
}
