pipeline {
  agent any

  stages {
    stage('install') {
      steps {
        dir('front') {
          nodejs(nodeJSInstallationName: 'nodejs') {
              sh 'npm install'
          }
        }
      }
    }
  }
}
